commit10

diff --git a/themes/after-dark/bin/install b/themes/after-dark/bin/install
--- a/themes/after-dark/bin/install
+++ b/themes/after-dark/bin/install
@@ -1,33 +1,16 @@
-#!/bin/sh -e
-#
-# Copyright (C) 2019  Josh Habdas <jhabdas@protonmail.com>
-#
-# This file is part of After Dark.
-#
-# After Dark is free software: you can redistribute it and/or modify
-# it under the terms of the GNU Affero General Public License as published
-# by the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# After Dark is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU Affero General Public License for more details.
-#
-# You should have received a copy of the GNU Affero General Public License
-# along with this program.  If not, see <https://www.gnu.org/licenses/>.
-#
+#!/bin/sh
+set -e
 
 validate_hugo () {
    # Exit with error if hugo is not installed
    if ! hash hugo 2>/dev/null ; then
-     echo "Error: After Dark requires Hugo version 0.51 or greater" >&2; exit 1
+     echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
    fi
 
    # Exit with error if not minimum required hugo version
-   re="v(0\d*\.([5-9][1-9]|[6-9])|[1-9]).*"
+   re="v(0\d*\.([4-9][4-9]|[5-9])|[1-9]).*"
    if ! hugo version | grep -qE "$re" ; then
-      echo "Error: After Dark requires Hugo version 0.51 or greater" >&2; exit 1
+      echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
    fi
 }
 
@@ -49,8 +32,8 @@ create_site () {
 
 download_theme () {
    echo "Downloading the latest version of After Dark ..."
-   LATEST_META=$(wget -qO - https://registry.npmjs.org/after-dark/latest)
-   vers=$(echo "$LATEST_META" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   THEME_META=$(wget -qO - https://registry.npmjs.org/after-dark/latest)
+   vers=$(echo "$THEME_META" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/after-dark
    wget -qO - https://registry.npmjs.org/after-dark/-/after-dark-"$vers".tgz | tar --strip-components=1 -xz -C themes/after-dark
    echo "Version $vers downloaded to $SITE_DIR/themes/after-dark"
@@ -60,7 +43,7 @@ download_module () {
    [ -z "$1" ] && { echo "Error: Attempt to download undefined module" >&2; exit 1; }
    echo "Downloading $1 module for After Dark ..."
    meta=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
-   vers=$(echo "$meta" | grep -oE "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   vers=$(echo "$meta" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
    mkdir -p themes/"$1"
    wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
    echo "Version $vers downloaded to $SITE_DIR/themes/$1"
@@ -69,44 +52,35 @@ download_module () {
 configure_theme () {
    echo "Configuring basic After Dark theme settings ..."
    tee "config.toml" > /dev/null <<TOML
-baseurl = "https://domain.example" # Controls base URL sitewide
+baseurl = "https://donate.habd.as" # Controls base URL sitewide
 languageCode = "en-US" # Controls site language
 title = "After Dark" # Homepage title and page title suffix
 paginate = 11 # Number of posts to show before paginating
-copyright = "Copyright &copy; Copyright Owner. Licensed under <a target=\"_blank\" rel=\"external noopener license\" href=\"https://creativecommons.org/licenses/by-nd/4.0/\">CC-BY-ND-4.0</a>." # Optional, remove to suppress copyright notices
 
 # Controls default theme and theme components
 theme = [
-  "fractal-forest", # OBSD
-  "after-dark" # AGPL-3.0-or-later
+  "fractal-forest",
+  "after-dark"
 ]
 
-disableLiveReload = false # Optional, set true to disable live reload
 enableRobotsTXT = true # Suggested, enable robots.txt file
-sectionPagesMenu = "main" # Enable menu system for lazy bloggers
+disqusShortname = "" # Deprecated, add Disqus shortname for comments
 
-[markup.goldmark.renderer]
-  unsafe = true # Optional, allows HTML inside your CommonMark content
-[markup.tableOfContents]
-  startLevel = 1 # Suggested, draws TOC using all heading levels
-  endLevel = 6 # Suggested, draws TOC using all heading levels
-[markup.highlight]
-  noClasses = false # Suggested, used for custom syntax highlighting
+pygmentsCodefences = true # Suggested, highlight fenced code blocks
+pygmentsUseClasses = true # Required for custom syntax highlighting
+
+sectionPagesMenu = "main" # Enable menu system for lazy bloggers
+footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
 
 [params]
   description = "" # Suggested, controls default description meta
   author = "" # Optional, controls author name display on posts
-  hide_author = false # Optional, set true to hide author name on posts
-  disable_csp = false # Optional, set true to disable content security policy
+  hide_author = true # Optional, set true to hide author name on posts
+  show_menu = false # Optional, set true to enable section menu
+  powered_by = true # Optional, set false to disable footer credits
   images = [
     "https://source.unsplash.com/collection/983219/2000x1322"
   ] # Suggested, controls default Open Graph images
-
-[params.layout.menu.main]
-  hidden = true # Optional, set false or remove to show section menu
-
-[params.layout.footer]
-  hidden = false # Optional, set true to hide footer
 
 [params.modules.fractal_forest]
   enabled = true # Optional, set false to disable module
@@ -115,33 +89,22 @@ TOML
 }
 
 update_archetypes () {
-   echo "Updating the default content archetype ..."
+   echo "Updating site default content archetype ..."
    rm -f archetypes/default.md
    cp themes/after-dark/archetypes/default.md archetypes
 }
 
-create_welcome_post () {
-   echo "Creating welcome post ..."
-   hugo new post/welcome.md 1>/dev/null
-}
-
-serve_site () {
-   echo "Starting site server ..."
-   hugo serve --buildDrafts --navigateToChanged --port 1313 1>/dev/null &
-}
-
 generate_help_docs () {
    echo "Generating help documentation ..."
-   THEME_PATH=themes/after-dark
-   meta_path="$THEME_PATH"/data/npm
-   mkdir -p "$meta_path" && echo "$LATEST_META" | tr '\r\n' ' ' > "$meta_path"/latest.json
-   cd "$THEME_PATH"/docs && mkdir themes && ln -s ../.. "$THEME_PATH"
-   hugo new validate.md --kind validate 1>/dev/null
+   meta_path=themes/after-dark/data/npm
+   mkdir -p "$meta_path" && echo "$THEME_META" | tr '\r\n' ' ' > "$meta_path"/latest.json
+   hugo new help/index.md --kind help 1>/dev/null
 }
 
-serve_help () {
+serve_help_docs () {
    echo "Starting help server ..."
-   hugo serve --disableLiveReload --port 1414 1>/dev/null &
+   sleep 1
+   hugo serve --buildExpired --disableLiveReload --port 1414 1>/dev/null &
 }
 
 echo "Welcome to the After Dark quick installer. Press CTRL-C at any time to abort."
@@ -153,18 +116,16 @@ download_theme
 update_archetypes
 download_module "fractal-forest"
 configure_theme
-create_welcome_post
-serve_site
 generate_help_docs
-serve_help
+serve_help_docs
 
 YELLOW='\033[0;33m'
 NC='\033[0m'
 
-printf "${YELLOW}Installation successful!${NC}\n"
+echo "Installation successful!"
 echo "Site created in $SITE_DIR_ABS"
-echo "Site server started at http://localhost:1313/"
-echo "To stop it run \"kill \$(ps aux | awk '/[h]ugo.*1313/ {print \$2}')\"."
 echo "Help server started at http://localhost:1414/"
-echo "To stop and restart it run \"./themes/after-dark/bin/help\"."
+echo "To stop it run \"kill \$(ps aux | awk '/[h]ugo.*1414/ {print \$2}')\"."
+echo "To update and start it again run \"./themes/after-dark/bin/help\"."
+printf "${YELLOW}Run \"cd $SITE_DIR && hugo serve\" to start your site.${NC}\n"
 echo "Thank you for choosing After Dark."
